### ISSUE TITLE
I cannt build it, please help me, thanks

### ISSUE THREAD

**Issue by crazyfox3** [twitter-archive/snowflake#1]
[warn]  module not found: com.twitter#ostrich;2.3.3
[warn] ==== local: tried
[warn]   /home/xichen/.ivy2/local/com.twitter/ostrich/2.3.3/ivys/ivy.xml
[warn]   -- artifact com.twitter#ostrich;2.3.3!ostrich.jar:
[warn]   /home/xichen/.ivy2/local/com.twitter/ostrich/2.3.3/jars/ostrich.jar
[warn] ==== local-libs: tried
[warn]   -- artifact com.twitter#ostrich;2.3.3!ostrich.jar:
[warn]   /usr/local/xichen/snowflake/libs/ostrich-2.3.3.jar
[warn] ==== localm2: tried
[warn]   /home/xichen/.ivy2/local/com/twitter/ostrich/2.3.3/ivy-2.3.3.xml
[warn]   -- artifact com.twitter#ostrich;2.3.3!ostrich.jar:
[warn]   /home/xichen/.ivy2/local/com/twitter/ostrich/2.3.3/ostrich-2.3.3.jar
[warn] ==== public: tried
[warn]   http://repo1.maven.org/maven2/com/twitter/ostrich/2.3.3/ostrich-2.3.3.pom
[warn]   -- artifact com.twitter#ostrich;2.3.3!ostrich.jar:
[warn]   http://repo1.maven.org/maven2/com/twitter/ostrich/2.3.3/ostrich-2.3.3.jar
[warn] ==== Scala-Tools Maven2 Repository: tried
[warn]   http://scala-tools.org/repo-releases/com/twitter/ostrich/2.3.3/ostrich-2.3.3.pom
[warn]   -- artifact com.twitter#ostrich;2.3.3!ostrich.jar:
[warn]   http://scala-tools.org/repo-releases/com/twitter/ostrich/2.3.3/ostrich-2.3.3.jar
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  ::          UNRESOLVED DEPENDENCIES         ::
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[warn]  :: com.twitter#ostrich;2.3.3: not found
[warn]  ::::::::::::::::::::::::::::::::::::::::::::::
[info] 
[warn] :: problems summary ::
[warn] :::: WARNINGS
[warn]      module not found: com.twitter#ostrich;2.3.3
[warn]  ==== local: tried
[warn]    /home/xichen/.ivy2/local/com.twitter/ostrich/2.3.3/ivys/ivy.xml
[warn]    -- artifact com.twitter#ostrich;2.3.3!ostrich.jar:
[warn]    /home/xichen/.ivy2/local/com.twitter/ostrich/2.3.3/jars/ostrich.jar
[warn]  ==== local-libs: tried
[warn]    -- artifact com.twitter#ostrich;2.3.3!ostrich.jar:
[warn]    /usr/local/xichen/snowflake/libs/ostrich-2.3.3.jar
[warn]  ==== localm2: tried
[warn]    /home/xichen/.ivy2/local/com/twitter/ostrich/2.3.3/ivy-2.3.3.xml
[warn]    -- artifact com.twitter#ostrich;2.3.3!ostrich.jar:
[warn]    /home/xichen/.ivy2/local/com/twitter/ostrich/2.3.3/ostrich-2.3.3.jar
[warn]  ==== public: tried
[warn]    http://repo1.maven.org/maven2/com/twitter/ostrich/2.3.3/ostrich-2.3.3.pom
[warn]    -- artifact com.twitter#ostrich;2.3.3!ostrich.jar:
[warn]    http://repo1.maven.org/maven2/com/twitter/ostrich/2.3.3/ostrich-2.3.3.jar
[warn]  ==== Scala-Tools Maven2 Repository: tried
[warn]    http://scala-tools.org/repo-releases/com/twitter/ostrich/2.3.3/ostrich-2.3.3.pom
[warn]    -- artifact com.twitter#ostrich;2.3.3!ostrich.jar:
[warn]    http://scala-tools.org/repo-releases/com/twitter/ostrich/2.3.3/ostrich-2.3.3.jar
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      ::          UNRESOLVED DEPENDENCIES         ::
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[warn]      :: com.twitter#ostrich;2.3.3: not found
[warn]      ::::::::::::::::::::::::::::::::::::::::::::::
[info] 

what should I do?

**Comment by ryanking** [comment]
Sorry, I don't think ostrich 2.3.3 is published anymore. Try updating to a newer version. Or i'll do it when i'm back in the office next week.

**Comment by crazyfox3** [comment]
ok, waiting for your updates

**Comment by ryanking** [comment]
I just pushed some updates that should help. Can you try again?

**Comment by Nyu2Y** [comment]
update had returned to normal. thank u

**Comment by ryanking** [comment]
good. closing
