### ISSUE TITLE
 Duplicate id 

### ISSUE THREAD

**Issue by gavenpeng** [twitter-archive/snowflake#11]
created test_id error! Error: ER_DUP_ENTRY: Duplicate entry 'f264bYg001' for key 'PRIMARY' the Duplicate id is 49，this is error msg while insert db

**Comment by gavenpeng** [comment]
this is my product config
new SnowflakeConfig {
serverPort = 7610
datacenterId = 0
workerIdMap = Map(0 -> InetAddress.getLocalHost.getHostName)
// workerIdMap = Map(1 -> "cmg1.chamago.com")
workerIdZkPath = "/snowflake-servers"
skipSanityChecks = true
startupSleepMs = 10000
thriftServerThreads = 10

zookeeperClientConfig = new ZookeeperClientConfig {
hostList = "cmg1.chamago.com:2181,cmg2.chamago.com:2181,cmg3.chamago.com:2181"
}

reporterConfig = new ReporterConfig {
scribeCategory = "snowflake"
scribeHost = "localhost"
scribePort = 1463
scribeSocketTimeout = 5000
flushQueueLimit = 100000
}

admin = new AdminServiceConfig {
httpPort = 9991
}

loggers = new LoggerConfig {
handlers = new FileHandlerConfig {
filename = "snowflake2.log"
level = Logger.TRACE
}
}

}

**Comment by ryanking** [comment]
Your configuration is problematic. The way you construct the worker id map means that all workers will get the same id. There is therefore no guarantee of unique ids.

**Comment by gavinpeng** [comment]
thanks you ryanking,my configuration is for only one worker,no multi worker,datacenterId ,worker and datacenterId only one,so no all worker i think ,please you checked,thanks very much

**Comment by gavinpeng** [comment]
you point you here is problematic,because my server only one worker in one datacenter,please 
help me,how i do the configuration about the worker,thanks you.
