### ISSUE TITLE
Write a 'getting started' documentation

### ISSUE THREAD

**Issue by AlexCzar** [twitter-archive/snowflake#17]
It's quite hard to get from github to running snowflake, especially without prior knowledge of scala, sbt and zookeeper.

**Comment by bdd** [comment]
Snowflake bulids with Maven so sbt is irrelevant. Due to the critical nature of ID generation a strongly consistent way of assigning IDs to workers is needed and ZooKeeper fits the bill.

Hopefully we'll make documentation more clear in upcoming months.

**Comment by indykish** [comment]
We have forked and built a snowflake.deb  for our use. The current README.md is updated here https://github.com/indykish/snowflake with sample code snippet on how we use it in scala 2.10.3, and a debian bundle is available as well.

Hope this helps. Would be glad to hear your feedback.
