### ISSUE TITLE
who can help me ? a simple problem

### ISSUE THREAD

**Issue by Nyu2Y** [twitter-archive/snowflake#2]
Use SBT and update successed . but Failure to compile .  
The error informations are as follows： 
[error] Error running auto-compile-thrift-java: java.io.IOException: Cannot run program "thrift": java.io.IOException: error=2, No such file or directory  
[error] Error running auto-compile-thrift-ruby: java.io.IOException: Cannot run program "thrift": java.io.IOException: error=2, No such file or directory
   How to Solve This Problem?  
   thank u for read  
   The novice needs to help. Please

**Comment by xianxu** [comment]
Seems you don't have thrift on your path?

**Comment by ryanking** [comment]
Try installing thrift from http://thrift.apache.org/

**Comment by Nyu2Y** [comment]
thank u . the answer is right . 

# and i find a website which tell us how to Installing Snowflake . i think it is a valuable resource for me .
-   Here are the prerequisites:
  -   Java 6 (1.6)
  -   sbt (simple-build-tool) – http://code.google.com/p/simple-build-tool/
  -   thrift – http://incubator.apache.org/thrift/
-   The install process is fairly straightforward:
  -   Clone the repo: git clone http://github.com/twitter/snowflake.git
  -   Edit project/build.properties to use sbt.version=0.7.4
  -   sbt update
  -   sbt compile
  -   sbt test
  -   Copy one of the configs into 
           \*   /etc: cp config/development2.conf  
           \*   /etc/unknown.conf 
      Or you can also just use ‘sbt run -f config/development2.conf’.
  -   Edit the conf and add a unique worker ID: worker_id = 1
  -   In the conf: skip_sanity_checks = false
  -   sbt run 
-   When you run the client like so:
        ------------------------------------------------------------------------------
        RUBYLIB=./target/gen-rb ./src/scripts/client_test.rb 1
        “192.168.0.103:7610,192.168.0.109:7610″ test-on
        -----------------------------------------------------------------------------
-   You should get something like this:
        ------------------------------------------------------------------------------
        557299556602089472 test-on 1 
        ------------------------------------------------------------------------------
-  [read in the original]
  -   http://www.codebelay.com/blog/2010/06/06/installing-snowflake/
    -  Moreover, I will thank all the people who helped me.
      xianxu, ryanking, barc, and crazyfox3 . thank u
