### ISSUE TITLE
isn't this prone to duplicate IDs ?

### ISSUE THREAD

**Issue by yangyangyyy** [twitter-archive/snowflake#24]
on the same server, it seems that the thrift server can be configured with multiple threads ("      serverOpts.workerThreads = thriftServerThreads
")

but inside the worker, sequence is a local var. so theoretically it's possible to get duplicates. no??

**Comment by bdd** [comment]
Notice the `synchronized` block:
https://github.com/twitter/snowflake/blob/snowflake-2010/src/main/scala/com/twitter/service/snowflake/IdWorker.scala#L71
