### ISSUE TITLE
another porbem . Thank you for the trouble you have go to

### ISSUE THREAD

**Issue by Nyu2Y** [twitter-archive/snowflake#3]
I installed thrift then SBT update successed, but something wrong with compie . 
## The message is 

[error] /home/qianniu/Documents/nyu/test1/twitter-snowflake-0047e1f/target/gen-java/com/facebook/fb303/FacebookService.java:138: no interface expected here
[error]   public static class Client extends org.apache.thrift.TServiceClient implements Iface {
[error]                                                       ^
[error] /home/qianniu/Documents/nyu/test1/twitter-snowflake-0047e1f/target/gen-java/com/facebook/fb303/FacebookService.java:834: cannot find symbol
[error] symbol  : class TBaseProcessor
[error] location: package org.apache.thrift
[error]   public static class Processor<I extends Iface> extends org.apache.thrift.TBaseProcessor implements org.apache.thrift.TProcessor {
.
.
.
[error] /home/qianniu/Documents/nyu/test1/twitter-snowflake-0047e1f/target/gen-java/com/facebook/fb303/FacebookService.java:751: cannot find symbol
[error] symbol  : variable ___manager
[error] location: class com.facebook.fb303.FacebookService.AsyncClient
[error]       ___manager.call(method_call);
[error]       ^
[error] Note: Some input files use unchecked or unsafe operations.
[error] Note: Recompile with -Xlint:unchecked for details.
[error] 100 errors
[info] == compile ==
## [error] Error running compile: javac returned nonzero exit code

How can I solve this problem?
thank u for read and sorry for my low English .

**Comment by Nyu2Y** [comment]
version number is unified between snowflake and thrift

**Comment by xianxu** [comment]
most likely thrift version's wrong. make sure you have the correct thrift
version installed.
