### ISSUE TITLE
Dependency error, while running 'sbt update'

### ISSUE THREAD

**Issue by yuvrajm** [twitter-archive/snowflake#5]
Hi,

I have downloaded snowflake via github, and installed sbt, however, after running 'sbt update', I get the following error:

unresolved dependency: org.jruby
unresolved dependency: org.markdown
unresolved dependency: org.freemarker

Screenshot is available on http://i40.tinypic.com/2qx9wuw.gif

**Comment by SethTisue** [comment]
I don't really know what's going on here, but if I rip out most of project/plugins/Plugins.scala, and replace it with just https://gist.github.com/01e9465fb1066db06243, then the libs are found

**Comment by jondot** [comment]
Had same issue. @SethTisue fix worked for me initially but something still fails (running sbt update):

```
    [error] sbt.ResolveException: unresolved dependency: com.twitter#scala-zookeeper-client;3.0.1: not found
    [info] == update ==
    [error] Error running update: sbt.ResolveException: unresolved dependency: com.twitter#scala-zookeeper-client;3.0.1: not found
    [info] 
    [info] Total time: 353 s, completed Jan 9, 2012 6:11:32 PM
    [info] 
    [info] Total session time: 509 s, completed Jan 9, 2012 6:11:32 PM
    [error] Error during build.
```

**Comment by OlegYch** [comment]
try adding back the default ivy repositories in Plugins.scala like this

override def ivyRepositories = Seq(Resolver.defaultLocal(None)) ++ repositories ++ super.ivyRepositories

although it appears you would need to build and publish locally https://github.com/twitter/scala-zookeeper-client yourself

good luck

**Comment by bdd** [comment]
Closing this before pushing the rewrite of Snowflake.
We don't build with sbt anymore.
